name: weekly-applyhome-excel
on:
  schedule:
    - cron: '0 23 * * 0'  # 월요일 08:00 KST == 일요일 23:00 UTC
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Excel (최근 2주, 전체 권역)
        env:
          ODCLOUD_SERVICE_KEY: ${{ secrets.ODCLOUD_SERVICE_KEY }}
          KAKAO_REST_KEY: ${{ secrets.KAKAO_REST_KEY }}
        run: |
          python - << 'PY'
from datetime import datetime, timezone, timedelta
import pandas as pd
from app import (two_weeks_range, build_cover_df, build_detail_df, build_combine_df, build_by_complex_df, build_excel, ALL_AREA_CODES)

start, end = two_weeks_range()
cover = build_cover_df(start, end, ALL_AREA_CODES)
detail = build_detail_df(cover)
combine = build_combine_df(detail)
bycx = build_by_complex_df(combine, detail, cover)
bytes_x = build_excel(bycx, cover, detail, combine)
fn = f"applyhome_{datetime.now(timezone(timedelta(hours=9))).strftime('%Y-%m-%d')}.xlsx"
open(fn, 'wb').write(bytes_x)
print('wrote', fn)
PY

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekly-excel
          path: applyhome_*.xlsx
